title: Empathetics
description: Simulation practice and feedback for professional education providers.
baseurl: ""
url: "https://empathetics.ai"

plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM  

include:
  - pages
