title: Empathetics
description: AI-powered clinical simulations for education, training, and public access through Clinichat
baseurl: "" 
url: "https://www.playfulhealth.com.au"

plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM  

include:
  - pages
